# These are all the cops that are disabled in the default configuration.
# encrypt email function uses dynamic finder method, so disabling this check
# TODO faced rubocop bug https://github.com/bbatsov/rubocop/issues/4751
Style/InlineComment:
  Description: "Avoid inline comments."
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Description: "Avoid chaining a method call on a do...end block."
  Enabled: false

Style/SymbolArray:
  Description: "Use %i or %I for arrays of symbols."
  Enabled: false

Style/Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Description: "Keep blank lines around access modifiers."
  Enabled: false

Style/EmptyLiteral:
  Description: "Prefer literals to Array.new/Hash.new/String.new."
  Enabled: false

Style/ClassAndModuleChildren:
  Description: "Checks style of children classes and modules."
  Enabled: false

Metrics/ClassLength:
  Description: "Avoid classes longer than 100 lines of code."
  Enabled: false

Metrics/MethodLength:
  Description: "Avoid methods longer than 10 lines of code."
  Enabled: false

Metrics/ParameterLists:
  Description: "Avoid parameter lists longer than three or four parameters."
  Enabled: false

Metrics/CyclomaticComplexity:
  Description: "Avoid complex methods."
  Enabled: false

Layout/ArrayAlignment:
  Description: >-
                 Align the elements of an array literal if they span more than
                 one line.
  Enabled: false

Style/RedundantPercentQ:
  Description: "Checks for %q/%Q when single quotes or double quotes would do."
  Enabled: false

Naming:
  Description: Check the naming of accessor methods for get_/set_.
  Enabled: false

#################### Lint ################################
### Warnings
Lint/AssignmentInCondition:
  Description: "Don't use assignment in conditions."
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Lint/MissingSuper:
  Description: >-
                  This cop checks for the presence of constructors and lifecycle callbacks
                  without calls to `super`.
  Enabled: false

Gemspec/DateAssignment:
  Description: 'Checks that `date =` is not used in gemspec file, it is set automatically when the gem is packaged.'
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  Description: >-
                 Checks the indentation of the next line after a line that
                 ends with a string literal and a backslash.
  Enabled: false
  EnforcedStyle: aligned
  SupportedStyles:
    - aligned
    - indented
  # By default the indentation width from `Layout/IndentationWidth` is used,
  # but it can be overridden by setting this parameter.
  IndentationWidth: ~
